### ISSUE TITLE
Support root-signed/system trusted CA certs

### ISSUE THREAD

**Issue by vito** [cloudfoundry-incubator/credhub-cli#22]
Our CredHub has a certificate signed by a root CA. Targeting it fails with `x509: certificate signed by unknown authority`. I should not have to specify `--ca-cert` in this case, and don't really have a CA cert on hand since it's a root CA. (I could probably derive it or download it from the CA or something, but still.)

**Comment by danjahner** [comment]
Hey @vito - By root CA, I assume you mean your certificate was signed by a publicly trusted authority? This previously worked, but we regressed to see if anyone would notice (oh, hey!) because enabling this functionality requires the overhead of compiling the mac binaries via a Darwin worker. 

Passing off to @crawsible for prioritization.

**Comment by vito** [comment]
Yep.

Also, been there. We had the exact same iteration cycles with Fly. :)

**Comment by topherbullock** [comment]
Also ran into this and was pretty heckin' confused. 
What's also annoying is that using `--skip-tls-validation` yells at me about being deprecated. 😭

**Comment by crawsible** [comment]
@vito @topherbullock did you see this on macOS or linux (or both)?

**Comment by vito** [comment]
Both.

**Comment by crawsible** [comment]
@vito this was shipped in 1.6.0. Can you try it out and close the issue once you've confirmed it works for you?
