### ISSUE TITLE
Feature suggestion: Credhub user and Credhub Password should be settable via ENV vars

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry-incubator/credhub-cli#26]
I have been thinking about the need for this for a while, but without SOCKS5 proxy support bbl and credhub would never be on the same machine, so it was sort of useless to provide `CREDHUB_SERVER` and `CREDHUB_CA_CERT` inside of `bbl print-env`

But, now that it seems socks5 proxying is feasible, then it also makes sense that BBL could print _all_ information needed to target credhub so that users aren't actually aware of what their credhub password is. I realize this may have been an intentional choice (everything else is ENV var settable) but interested in revisiting it.

I don't have any opinion on the name of the env vars, but if you let me know what you plan to use I could integrate them immediately into bbl for future support.

https://www.pivotaltracker.com/story/show/152941463

**Comment by evanfarrar** [comment]
Alternatively, is there any reason that we set a _user_ and not a _client_ in the bosh-deployment ops files for credhub? IIRC clients are for machines to auth, and users are for humans, and it seems impossible to say that the default credentials could be considered as corresponding to single person, more likely they will be used in CI mostly.

**Comment by crawsible** [comment]
Hey @evanfarrar, sorry for the delay. We're going to work on a few stories to bring the post-bbl bosh cli and credhub cli experience more in-line with one another:
* update the credhub.yml opsfile to create a uaa client for CLI use instead of a uaa user [#152941819](https://www.pivotaltracker.com/story/show/152941819)
* CLI will authenticate against the server automatically if `CREDHUB_SERVER`, `CREDHUB_CLIENT` and `CREDHUB_CLIENT_SECRET` are all set and the user executes a command [#154059387](https://www.pivotaltracker.com/story/show/154059387)
* CLI will respect a CredHub-specific https proxy env var instead of relying on the global `https_proxy` value. [#154059643](https://www.pivotaltracker.com/story/show/154059643)

To take full advantage of these features, `bbl print-env` should include commands to set `CREDHUB_CLIENT`, `CREDHUB_CLIENT_SECRET` and `CREDHUB_PROXY` -- the latter being the same value as `BOSH_ALL_PROXY`.

Does this sound good to you? Let me know if there are any additional quality-of-life improvements that could simplify the process of using after bbling up.

**Comment by evanfarrar** [comment]
Rad. You can close this out, my objective, a discussion and alignment, is achieved.

I think one forward looking thing to be aware of, given that you are aligning with BOSH_ALL_PROXY, is that BOSH_ALL_PROXY now* supports a funky alternate URI syntax whereby you may specify the private key path, jumpbox address, local ssh port, etc for a proxy if you set the BOSH_ALL_PROXY to something beginning with `socks5+ssh://`. I may give you a PR or feature request in the future as BBL tries to move to this declarative syntax rather than managing tunnels ourselves, which will provide a better user experience where the proxy starts and stops just in time as the BOSH cli communicates to the director.

(*Where "now" means whenever the next BOSH cli is released)

**Comment by crawsible** [comment]
@evanfarrar Cool, good to know. I'll reach out to @cppforlife to find out if there's a library we might be able to consume in our go CLI. As for the env vars that should be present in bbl print-env for the credhub CLI to work out of the box, should I drop a story in your icebox?

**Comment by crawsible** [comment]
Closing because Evan said "you can close this out" (and because we addressed this problem differently).
