### ISSUE TITLE
credhub interpolate of variables with whitespace before/after double parentheses fails.

### ISSUE THREAD

**Issue by HoffiMuc** [cloudfoundry-incubator/credhub-cli#85]
CLI Version: 2.6.1
Server Version: 2.5.9

`credhub interpolate --prefix /concourse/main/ --file env/env.yml`

I expected that variables with whitespace after '((' or before '))' would still be interpolated correctly (without the whitepaces)

only `something: ((varname))` will be interpolated correctly from credub,
but  `something: ((  varname  ))` would not be interpolated

is this intentional or a bug?

**Comment by ankeesler** [comment]
@HoffiMuc - thank you for reporting this. I believe this is intentional, but may not be the best design. It doesn't really follow the `be conservative in what you send, be liberal in what you accept` principle. Are you able to adhere to the overly-strict `something: ((varname))` format? I think that is the best path forward, for now (unless you are unable to adhere to that format in which we can talk about how to get you unblocked). I will talk to our team about this design in the meantime.

**Comment by HoffiMuc** [comment]
Well it's just that all the other tools are able to deal with whitespace, and having whitespaces around the variable will not get you an error, but the literal value with braces. So you detect the fact That something is wrong not before very late in some processes... maybe sometimes not before prod.

**Comment by ankeesler** [comment]
Fair point. If you upgrade your CLI to `2.6.2`, you will see error messages printed to `stderr` when the CLI cannot interpolate the variable. Would that help you catch things earlier in your process?

**Comment by HoffiMuc** [comment]
fine with me. This didn't stop me from anything to work ... thought it just was weird and wanted to report this weird feeling :)
